repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0 
    hooks:
      - id: black
        exclude: ^notebooks/
        name: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 
    hooks:
      - id: isort
        exclude: ^notebooks/
        name: isort
        args: ["--settings-path=pyproject.toml"]
  
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4 
    hooks:
      - id: flake8
        exclude: ^notebooks/